language: php
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  fast_finish: true
  allow_failures:
    - php: "hhvm"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"
    - php: "hhvm"

env:
  - SMARTY="2.6.*"
  - SMARTY="3.1.*"

before_install:
  - sudo apt-get update && travis_retry sudo apt-get --reinstall install -qq gettext language-pack-{et,pl}
  - dpkg --list | grep language-pack
  - locale -a
  # enable EZC for hhvm
  - test ! -f /etc/hhvm/php.ini || echo hhvm.enable_zend_compat=true | sudo tee -a /etc/hhvm/php.ini

install:
  - composer install --no-interaction --prefer-source

before_script:
  - make -C tests/i18n

script:
  - composer require --dev smarty/smarty=$SMARTY
  - phpunit --version
  - phpunit

# vim:ts=2:sw=2:et
